import test,{beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import { csvText,dayKey,reportFor,shiftDay,updateCart,validateProduct } from '../src/domain.js';
import { demoApi as api } from '../src/demoApi.js';
const values=new Map();
globalThis.localStorage={getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)};
Object.defineProperty(globalThis,'navigator',{value:{locks:{request:async(_name,action)=>action()}},configurable:true});
beforeEach(()=>values.clear());
const saleInput=(quantity=1)=>({paymentMethod:'Efectivo',customer:'Prueba',requestId:crypto.randomUUID(),items:[{productId:'P-001',quantity,expectedPrice:4.5}]});
test('fecha de Lima en el límite UTC',()=>{assert.equal(dayKey('2026-10-05T02:00:00Z'),'2026-10-04');assert.equal(shiftDay('2026-10-01',-1),'2026-09-30');assert.equal(dayKey(null),null);});
test('un día sin ventas muestra cero y no valores de muestra',()=>{const r=reportFor([],'2026-10-01','2026-10-01');assert.equal(r.total,0);assert.equal(r.ticket,0);assert.equal(r.margin,null);});
test('reportes excluyen anulaciones y usan detalles reales',()=>{
  const sales=[{soldAt:'2026-10-04T13:00:00Z',status:'active',total:10,items:2,method:'Yape',lines:[{productId:'A',name:'A',quantity:2,unitCost:3,total:10}]},{soldAt:'2026-10-04T13:00:00Z',status:'cancelled',total:100,items:20,method:'Efectivo',lines:[]}];
  const r=reportFor(sales,'2026-10-04','2026-10-04');assert.equal(r.total,10);assert.equal(r.units,2);assert.equal(r.margin,40);assert.equal(r.payments.find(p=>p.method==='Yape').percent,100);assert.equal(r.ranking[0].quantity,2);
});
test('reportes conservan la incertidumbre de registros históricos',()=>{const r=reportFor([{soldAt:null,status:'active',total:30,items:1},{soldAt:'2026-10-04T10:00:00Z',status:'active',total:10,items:1,method:'Efectivo',lines:[{productId:'A',name:'A',quantity:1,unitCost:null,total:10}]}],'2026-10-04','2026-10-04');assert.equal(r.unknownDates,1);assert.equal(r.margin,null);assert.equal(r.missingCost,1);});
test('carrito rechaza cantidades superiores al stock y fracciones inválidas',()=>{const p={id:'A',stock:3,price:1};assert.throws(()=>updateCart([],[p],'A',4));assert.throws(()=>updateCart([],[p],'A',1.001));assert.deepEqual(updateCart([{...p,quantity:1}],[p],'A',0),[]);});
test('productos validan números, nombre y precio',()=>{assert.throws(()=>validateProduct({name:'A',category:'A',unit:'unidad',stock:-1,minStock:0,cost:0,price:1}));assert.throws(()=>validateProduct({name:'A',category:'A',unit:'unidad',stock:0,minStock:0,cost:0,price:0}));});
test('dos reintentos del mismo cobro descuentan una sola vez',async()=>{const input=saleInput(),before=(await api.getProducts())[0].stock;const a=await api.createSale(input),b=await api.createSale(input);assert.equal(a.id,b.id);assert.equal((await api.getProducts())[0].stock,before-1);});
test('no se puede reutilizar una clave con otra cantidad',async()=>{const input=saleInput();await api.createSale(input);await assert.rejects(api.createSale({...input,items:[{productId:'P-001',quantity:2}]}));});
test('venta rechazada no modifica stock ni historial',async()=>{const before=await api.backup();await assert.rejects(api.createSale(saleInput(999999)));const after=await api.backup();assert.deepEqual(before.data,after.data);});
test('un cambio de precio exige revisar el cobro',async()=>{await assert.rejects(api.createSale({...saleInput(),items:[{productId:'P-001',quantity:1,expectedPrice:1}]}));});
test('anulación devuelve stock una sola vez',async()=>{const before=(await api.getProducts())[0].stock,s=await api.createSale(saleInput());await api.cancelSale(s.id,'Prueba');await api.cancelSale(s.id,'Reintento');assert.equal((await api.getProducts())[0].stock,before);assert.equal((await api.getSales()).find(x=>x.id===s.id).status,'cancelled');});
test('anulación conserva stock de productos archivados',async()=>{const s=await api.createSale(saleInput());await api.deleteProduct('P-001');await api.cancelSale(s.id,'Prueba');assert.equal((await api.backup()).data.archivedProducts[0].stock,3);});
test('crear productos no sobrescribe códigos existentes',async()=>{const p={name:'Prueba',category:'Abarrotes',unit:'unidad',stock:0,minStock:0,cost:1,price:2,supplier:''};const a=await api.saveProduct(p),b=await api.saveProduct(p);assert.notEqual(a.id,b.id);assert.equal((await api.getProducts()).length,14);});
test('editar un producto con versión antigua se rechaza',async()=>{const p=(await api.getProducts())[0];await api.createSale(saleInput());await assert.rejects(api.saveProduct({...p,expectedVersion:p.version},p.id));});
test('ajuste de stock se registra y no permite saldo negativo',async()=>{const p=(await api.getProducts())[0];await api.adjustStock(p.id,{quantity:2,reason:'Reposición',expectedVersion:p.version});assert.equal((await api.getProducts())[0].stock,5);assert.equal((await api.getMovements())[0].quantity,2);await assert.rejects(api.adjustStock(p.id,{quantity:-6,reason:'Corrección',expectedVersion:2}));});
test('proveedores se guardan, vinculan y no se eliminan con productos activos',async()=>{await api.saveSupplier({name:'Nuevo',contact:'Contacto',phone:'999'});const supplier=(await api.getSuppliers()).find(s=>s.name==='Nuevo');await api.saveProduct({name:'Prueba',category:'A',unit:'unidad',stock:0,minStock:0,cost:0,price:1,supplier:'Nuevo'});await assert.rejects(api.deleteSupplier(supplier.id));});
test('configuración persiste y cajero no puede modificarla',async()=>{const settings={...await api.getSettings(),name:'Prueba Bodega'};await api.saveSettings(settings);assert.equal((await api.getSettings()).name,'Prueba Bodega');localStorage.setItem('bodega-norte:demo-role','cashier');await assert.rejects(api.saveSettings(settings));await assert.rejects(api.deleteProduct('P-001'));});
test('exportación CSV neutraliza fórmulas y escapa comillas',()=>{assert.equal(csvText([['=2+2','a"b',-2]]),'\ufeff"\'=2+2","a""b","-2"');});
