-- Esquema privado de Bodega Norte para Supabase PostgreSQL.
-- Ejecutar en el SQL Editor de Supabase o con una migración autorizada.

CREATE SCHEMA IF NOT EXISTS bodega_norte;
REVOKE ALL ON SCHEMA bodega_norte FROM PUBLIC;

CREATE TABLE IF NOT EXISTS bodega_norte.categories (
  category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS bodega_norte.suppliers (
  supplier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  contact_name VARCHAR(120),
  phone VARCHAR(30),
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS bodega_norte.products (
  product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(160) NOT NULL,
  category_id INTEGER NOT NULL REFERENCES bodega_norte.categories(category_id),
  supplier_id INTEGER REFERENCES bodega_norte.suppliers(supplier_id),
  unit VARCHAR(30) NOT NULL,
  stock NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (stock >= 0),
  min_stock NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (min_stock >= 0),
  cost NUMERIC(12,2) NOT NULL CHECK (cost >= 0),
  sale_price NUMERIC(12,2) NOT NULL CHECK (sale_price > 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bodega_norte.sales (
  sale_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_number VARCHAR(60) NOT NULL UNIQUE,
  payment_method VARCHAR(30) NOT NULL CHECK (payment_method IN ('Efectivo', 'Yape', 'Plin', 'Tarjeta')),
  total NUMERIC(12,2) NOT NULL CHECK (total >= 0),
  sold_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bodega_norte.sale_items (
  sale_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id INTEGER NOT NULL REFERENCES bodega_norte.sales(sale_id),
  product_id INTEGER NOT NULL REFERENCES bodega_norte.products(product_id),
  quantity NUMERIC(12,2) NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price > 0),
  line_total NUMERIC(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED
);

CREATE INDEX IF NOT EXISTS ix_products_low_stock
  ON bodega_norte.products(stock, min_stock) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS ix_products_category_id
  ON bodega_norte.products(category_id);
CREATE INDEX IF NOT EXISTS ix_products_supplier_id
  ON bodega_norte.products(supplier_id);
CREATE INDEX IF NOT EXISTS ix_sale_items_product_id
  ON bodega_norte.sale_items(product_id);
CREATE INDEX IF NOT EXISTS ix_sale_items_sale_id
  ON bodega_norte.sale_items(sale_id);
CREATE INDEX IF NOT EXISTS ix_sales_sold_at
  ON bodega_norte.sales(sold_at DESC);

-- El acceso se realiza desde el backend MVC con una conexión privada.
-- Se mantiene RLS como defensa adicional y el esquema no se expone a la Data API.
ALTER TABLE bodega_norte.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE bodega_norte.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE bodega_norte.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE bodega_norte.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE bodega_norte.sale_items ENABLE ROW LEVEL SECURITY;
